# CodeMind Rancher Compose Configuration
# Conversion from Docker to Rancher for all CodeMind services
# Usage: rancher up -d

.catalog:
  name: CodeMind
  version: v1.0.0
  description: Smart Claude Code CLI with intelligent tool selection and monitoring
  minimum_rancher_version: v1.6.0

services:
  # PostgreSQL Database with pgvector
  codemind-database:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: codemind
      POSTGRES_USER: codemind
      POSTGRES_PASSWORD: codemind123
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
    volumes:
      - codemind_postgres_data:/var/lib/postgresql/data
      - ./src/database/schema.postgres.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    ports:
      - "5432:5432"
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    health_check:
      healthy_threshold: 2
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
      response_timeout: 2000
      strategy: recreate
      port: 5432
      unhealthy_threshold: 3
    
  # Redis Cache & Message Queue  
  codemind-redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    volumes:
      - codemind_redis_data:/data
    ports:
      - "6379:6379"
    labels:
      io.rancher.container.pull_image: always
    health_check:
      healthy_threshold: 2
      initializing_timeout: 30000
      interval: 2000
      port: 6379
      reinitializing_timeout: 30000
      response_timeout: 2000
      strategy: recreate
      unhealthy_threshold: 3

  # Neo4j Graph Database
  codemind-neo4j:
    image: neo4j:5.15-community
    restart: unless-stopped
    environment:
      NEO4J_AUTH: neo4j/codemind123
      NEO4J_dbms_memory_heap_initial__size: 512m
      NEO4J_dbms_memory_heap_max__size: 1G
      NEO4J_dbms_memory_pagecache_size: 256m
    volumes:
      - codemind_neo4j_data:/data
      - codemind_neo4j_logs:/logs
    ports:
      - "7474:7474"
      - "7687:7687"
    labels:
      io.rancher.container.pull_image: always
    health_check:
      healthy_threshold: 2
      initializing_timeout: 60000
      interval: 5000
      port: 7474
      reinitializing_timeout: 60000
      response_timeout: 3000
      strategy: recreate
      unhealthy_threshold: 3

  # MongoDB Document Database  
  codemind-mongodb:
    image: mongo:7.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: codemind
      MONGO_INITDB_ROOT_PASSWORD: codemind123
      MONGO_INITDB_DATABASE: codemind
    volumes:
      - codemind_mongodb_data:/data/db
    ports:
      - "27017:27017"
    labels:
      io.rancher.container.pull_image: always
    health_check:
      healthy_threshold: 2
      initializing_timeout: 60000
      interval: 2000
      port: 27017
      reinitializing_timeout: 60000
      response_timeout: 2000
      strategy: recreate
      unhealthy_threshold: 3

  # CodeMind API Service
  codemind-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: codemind-api:latest
    restart: unless-stopped
    depends_on:
      - codemind-database
      - codemind-redis
      - codemind-neo4j
      - codemind-mongodb
    environment:
      NODE_ENV: production
      PORT: 3004
      DB_HOST: codemind-database
      DB_PORT: 5432
      DB_NAME: codemind
      DB_USER: codemind
      DB_PASSWORD: codemind123
      REDIS_HOST: codemind-redis
      REDIS_PORT: 6379
      NEO4J_URI: bolt://codemind-neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: codemind123
      MONGO_URI: mongodb://codemind:codemind123@codemind-mongodb:27017/codemind?authSource=admin
      LOG_LEVEL: info
    ports:
      - "3004:3004"
    volumes:
      - ./logs:/app/logs
      - /workspace:/workspace:ro
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    links:
      - codemind-database:database
      - codemind-redis:redis
      - codemind-neo4j:neo4j
      - codemind-mongodb:mongodb
    health_check:
      healthy_threshold: 2
      initializing_timeout: 60000
      interval: 5000
      port: 3004
      request_line: GET /health HTTP/1.1
      reinitializing_timeout: 60000
      response_timeout: 3000
      strategy: recreate
      unhealthy_threshold: 3

  # CodeMind Dashboard
  codemind-dashboard:
    build:
      context: .
      dockerfile: docker/docker/dashboard.Dockerfile
    image: codemind-dashboard:latest
    restart: unless-stopped
    depends_on:
      - codemind-database
      - codemind-redis
      - codemind-neo4j
      - codemind-mongodb
    environment:
      NODE_ENV: production
      DASHBOARD_PORT: 3005
      DB_HOST: codemind-database
      DB_PORT: 5432
      DB_NAME: codemind
      DB_USER: codemind
      DB_PASSWORD: codemind123
      REDIS_HOST: codemind-redis
      REDIS_PORT: 6379
      REDIS_URL: redis://codemind-redis:6379
      NEO4J_URI: bolt://codemind-neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: codemind123
      MONGO_URI: mongodb://codemind:codemind123@codemind-mongodb:27017/codemind?authSource=admin
      LOG_LEVEL: info
    ports:
      - "3005:3005"
    volumes:
      - ./logs:/app/logs
      - /workspace:/workspace:ro
    labels:
      io.rancher.container.pull_image: always
    links:
      - codemind-database:database
      - codemind-redis:redis
      - codemind-neo4j:neo4j
      - codemind-mongodb:mongodb
    health_check:
      healthy_threshold: 2
      initializing_timeout: 60000
      interval: 5000
      port: 3005
      reinitializing_timeout: 60000
      response_timeout: 3000
      strategy: recreate
      unhealthy_threshold: 3

  # CodeMind Orchestrator
  codemind-orchestrator:
    build:
      context: .
      dockerfile: docker/docker/orchestrator.Dockerfile
    image: codemind-orchestrator:latest
    restart: unless-stopped
    depends_on:
      - codemind-database
      - codemind-redis
    environment:
      NODE_ENV: production
      ORCHESTRATOR_PORT: 3006
      DB_HOST: codemind-database
      DB_PORT: 5432
      DB_NAME: codemind
      DB_USER: codemind
      DB_PASSWORD: codemind123
      REDIS_HOST: codemind-redis
      REDIS_PORT: 6379
      LOG_LEVEL: info
    ports:
      - "3006:3006"
    volumes:
      - ./logs:/app/logs
      - /workspace:/workspace:ro
    labels:
      io.rancher.container.pull_image: always
    links:
      - codemind-database:database
      - codemind-redis:redis
    health_check:
      healthy_threshold: 2
      initializing_timeout: 60000
      interval: 5000
      port: 3006
      reinitializing_timeout: 60000
      response_timeout: 3000
      strategy: recreate
      unhealthy_threshold: 3

# Rancher Load Balancer Configuration
lb:
  image: rancher/lb-service-haproxy:v0.9.1
  ports:
    - 80:80/tcp
    - 443:443/tcp
  labels:
    io.rancher.container.agent.role: environmentAdmin,agent
    io.rancher.container.agent_service.drain_provider: true
    io.rancher.container.create_agent: true
    io.rancher.loadbalancer.target.codemind-api: 3004=3004
    io.rancher.loadbalancer.target.codemind-dashboard: 3005=3005
    io.rancher.loadbalancer.target.codemind-orchestrator: 3006=3006