name: codeseeker
base: core22
version: '1.7.2'
title: CodeSeeker
license: MIT
summary: Graph-powered code intelligence for Claude Code and AI assistants
description: |
  CodeSeeker builds a knowledge graph of your codebase—not just embeddings—so
  Claude understands how your code actually connects.

  An MCP server that gives AI assistants semantic code search and knowledge
  graph traversal. Works with Claude Code, GitHub Copilot, Cursor, and Claude Desktop.

  Features:
  - Hybrid Search: Vector + text + path search with Reciprocal Rank Fusion
  - Knowledge Graph: Maps imports, calls, extends, implements relationships
  - Auto-Detected Patterns: Learns your project's coding standards
  - Graph RAG: Retrieval-Augmented Generation using code relationships
  - Local Storage: All data stored in .codeseeker/ - no external services

  Quick Start:
    1. snap install codeseeker
    2. codeseeker install --vscode    # or --cursor, --windsurf
    3. Restart your IDE

  Verify Installation:
    Ask your AI assistant: "What CodeSeeker tools do you have?"

contact: https://github.com/jghiringhelli/codeseeker/issues
issues: https://github.com/jghiringhelli/codeseeker/issues
source-code: https://github.com/jghiringhelli/codeseeker
website: https://github.com/jghiringhelli/codeseeker

grade: stable
confinement: classic

apps:
  codeseeker:
    command: bin/node $SNAP/lib/node_modules/codeseeker/bin/codeseeker.js
    plugs:
      - home
      - network
      - network-bind

parts:
  codeseeker:
    plugin: npm
    source: https://registry.npmjs.org/codeseeker/-/codeseeker-1.7.2.tgz
    npm-include-node: true
    npm-node-version: "18.20.5"
    build-packages:
      - python3
      - make
      - g++
    stage-packages:
      - libsqlite3-0
